### ISSUE TITLE
Share to Facebook Story not working

### ISSUE THREAD

**Issue by steo-ml** [react-native-share/react-native-share#1196] opened 2022-05-06 09:32 UTC
Sharing to `Social.FACEBOOK_STORIES` doesn't seem to be working on Android. I was testing out on my app, and then tried out the example app to see if I was doing something wrong, but it doesn't work in the example app either. I have the Facebook app installed and signed in. `appId` is provided.

Sharing to `Social.INSTAGRAM_STORIES` works. Sharing via `Share.open()` and then choosing Facebook Story works.

### Steps to reproduce
1. Press Share to FB Story button in the example app

### Expected behaviour
Should open up Facebook Story share screen

### Actual behaviour
A toast saying "Processing..." appears and nothing happens after that

### Environment
- **React Native version**: 0.66.4
- **React Native platform + platform version**: Android 10.0, Android Studio emulator
- **Typescript version** (if using typescript): N/A

### react-native-share
**Version**: master (cloned this repo and ran the example app)

### Link to repo (highly encouraged)
The example folder of this repo

**Comment by mikehardy** [comment] 2022-05-06 13:42
With apologies, I personally won't have the time to look into this and I'm not sure any other maintainers will. That's important to say, to set expectations

Best advice is to roll up sleeves, instrument the code in java with appropriate System.err.printlns before API calls with parameters listed out and after to see what's going on and consult associated API docs

The code here is not too complicated and the problem is probably small - any associated PR can be merged+released almost immediately after discovery of the issue

**Comment by steo-ml** [comment] 2022-05-09 04:50
So I've taken a look at the Java code, and found some differences between `FacebookStoriesShare` and `InstagramStoriesShare`:
![image](https://user-images.githubusercontent.com/80666855/167341734-aecbfde9-8a09-45e9-8046-e6c85eb681a5.png)
![image](https://user-images.githubusercontent.com/80666855/167341747-5432b112-dd2c-4128-bfbb-2437c733fe9b.png)

Facebook was using the ShareFile constructor with 4 parameters while Instagram was using the one with 5, so I replicated these two lines from `InstagramStoriesShare` into `FacebookStoriesShare` and it did the trick. However, I'm not very familiar with native code, so I'm not sure if this is the correct fix to this issue.

**Closed** 2022-06-22 21:21 UTC
Labels: bug
