### ISSUE TITLE
Meta data name is overriding custom title

### ISSUE THREAD

**Issue by Hezron-Nelapati** [react-native-share/react-native-share#1182] opened 2022-04-14 11:35 UTC
### Steps to reproduce
1.  Use this code for setting options

```javascript
const options = Platform.select({
      ios: {
        activityItemSources: [
          {
            // For sharing url with custom title.
            placeholderItem: { type: "url", content: url },
            item: {
              default: { type: "url", content: url },
            },
            subject: {
              default: title,
            },
            linkMetadata: { originalUrl: url, url, title },
          },
        ],
      },
      default: {
        title,
        subject: title,
        message: `${url}`,
        failOnCancel: false,
        filename,
      },
    });

    Share.open(options);
```

### Expected behaviour
Custom name should be shown while sharing

### Actual behaviour
Name in Link Meta Data is showing

### Environment
- **React Native version**: 0.61.5
- **React Native platform: IOS + platform version**: iOS 15
- **Typescript version** (if using typescript): No

### react-native-share
**Version**:  7.3.7

**Comment by mikehardy** [comment] 2022-04-14 17:46
> React Native version: 0.61.5

I'm shocked that's even working. I think that implies you are still building on Xcode 11? Or at least 12.4. Using older SDKs for iOS (they are bundled with Xcode). I'm not sure it will have an effect or not but using up to date toolchains (react-native 0.67.x at least - use https://react-native-community.github.io/upgrade-helper/ to move to most recent patch release of each minor version at a time) and Xcode 13.x may help

Otherwise, this will need triage I suppose. Does it still reproduce if you use our example - modified for your case - with up to date Xcode ?

**Comment by Hezron-Nelapati** [comment] 2022-04-14 18:32
@mikehardy HI, My xcode version 13.3.1 and i'm using the example mentioned in the docs "For sharing url with custom title".
So, the only options is to update the react native version (or) any lower version of this package supports my react native version with custom title feature.

**Comment by mikehardy** [comment] 2022-04-14 18:40
Fascinating - you must have some patches you apply to react-native in order to get Xcode 13.3.1 to build react-native 0.61.5 because I know that it nothing below react-native 0.64.5 compiles out of the box with any Xcode higher than 12.4.

Anyway, I'm not that surprised it did not help. I don't think updating or downgrading will matter, this needs further analysis and the location of the error (or perhaps the platform limitation) will be inside this module.

I won't have time to help triage, sorry, but here's my process:
- go into node_modules and add pre-post console.log to all relevant API consoles where you print out what step you are on and what the parameters / return values to/from the native APIs are
- also in node_modules, in the iOS code, search internet for how to add logging or look for code in the module that already does logging (RCTLog maybe?) since I always forget, and do the same in the objective-c code for this module before/after it calls iOS system APIs logging out parameters and return values
- search the system APIs we call for their documentation on apple's dev website

Re-run your test on a real device plugged in to your development machine using a build from Xcode so you get a nice console view of all log messages

Compare log messages you receive with documentation for relevant API calls, make deductions from there on what is possible vs what is happening, and if what you want is possible but not happening, alter code based on results from testing...

**Comment by Hezron-Nelapati** [comment] 2022-04-14 19:36
Hi @mikehardy , seems like your trying to override the title provided in the ActivityItemSource with title in metadata fetched from server. I just commented that line and it's working for me now. 

<img width="807" alt="Screenshot 2022-04-15 at 1 03 20 AM" src="https://user-images.githubusercontent.com/62951600/163463367-f1185359-6204-4eda-a967-c5ff2236bf71.png">

Thanks

**Comment by mikehardy** [comment] 2022-04-14 19:55
Okay - so, is this an issue with the library that should be fixed or is this really closed? You can always use patch-package to make a local edit semi-permanent with a good developer experience, but if this is an issue and you propose a PR that works in the general case and in your specific case, we can merge it...

**Comment by Hezron-Nelapati** [comment] 2022-04-14 20:48
Hi @mikehardy , this is an issue with package, your are overriding the title value from metadata even if the title is passed from react native. So, before overriding the title value, we can check if a value is already present in title, if present, then we can omit overriding the value came from metadata.

**Comment by mikehardy** [comment] 2022-04-14 21:19
Okay - reopening - per your suggestion it seems the fix is to alter logic to:

- check for title first
- if title supplied, use it
- if no title, then use metadata value

Would welcome a PR!

**Comment by Hezron-Nelapati** [comment] 2022-04-15 01:45
Hi @mikehardy, i made PR https://github.com/react-native-share/react-native-share/pull/1184, look into it.

**Comment by mikehardy** [comment] 2022-04-15 04:00
Fixed and released awesome 😎

**Closed by mikehardy** 2022-04-15 04:00 UTC
Labels: bug, help wanted, good first issue
