### ISSUE TITLE
Share.opennot returning promise in android

### ISSUE THREAD

**Issue by ShahilMangroliya** [react-native-share/react-native-share#1405] opened 2023-06-23 05:11 UTC
### Steps to reproduce
1. const shareRes = await Share.open({
  url:url,
  message: text,
});
2. It's not resolving promise on android however it's in ios and older versions of react-native-share like 8.2.2

### Expected behaviour
It should go to next line after sharing complete

### Actual behaviour
It just stuck at await

### Environment
- **React Native version**:0.71.11
- **Android Version**:12

### react-native-share
**Version**: 9.0.2

**Comment by robinsoncol** [comment] 2023-06-27 05:48
I'm also running into this issue on iOS

**Comment by robinsoncol** [comment] 2023-07-05 20:25
@MateusAndrade we can close this issue now

**Comment by jaaywags** [comment] 2023-07-08 03:39
Seeing this issue on Android, version 9.2.1 on Android

**Comment by robinsoncol** [comment] 2023-07-08 05:20
@jaaywags What are you trying to share?

**Comment by jaaywags** [comment] 2023-07-08 05:36
@robinsoncol I was able to reproduce the issue with the following code. I call this function to initiate the share, then click outside of the action sheet without sending the file to any other app.

```javascript
// I am using exporting to control spinner and disable button
setExporting(true);
try {
  const rows = 'columns1,column2,column3\nr1c1,c1c2,r1c3\n,r2c1,r2c2,r2c3\nr3c1,r3c2,r3c3';

  const filename = `${dayjs().format('MMDDYYYYTHHmmss')}`;
  let path = '';
  if (Platform.OS === 'android') {
    // Use base64 - file does not work on Android
    path = `data:text/csv;base64,${new Buffer(rows).toString("base64")}`;
  } else {
    // Write the file - base64 does not work on iOS
    path = `file/${RNFS.TemporaryDirectoryPath}/${filename}.csv`;
    await RNFS.writeFile(path, rows, 'utf8');
  }

  // Temp fix for this issue 1405
  Platform.OS === 'android' && setExporting(false);

  // Share file
  await Share.open({
    url: path,
    failOnCancel: false,
    subject: `MyApp - Expor Data - ${filename}`,
  });

  // Post share - never hit
} catch (error) {
  // Handle error - never hit
}

setExporting(false);
```

**Comment by ncote3** [comment] 2023-07-17 13:16
> @robinsoncol I was able to reproduce the issue with the following code. I call this function to initiate the share. The issue happens if I share the file with other apps (E.g. Gmail) or not (by click outside of the action sheet).
> 
> This only happens on Android. iOS is fine.
> 
> ```js
> import Share from 'react-native-share';
> import RNFS from 'react-native-fs';
> import { Buffer } from 'buffer';
> 
> // ...
> 
> // I am using exporting to control spinner and disable button
> setExporting(true);
> try {
>   const rows = 'column1,column2,column3\nr1c1,r1c2,r1c3\n,r2c1,r2c2,r2c3\nr3c1,r3c2,r3c3';
> 
>   const filename = `${dayjs().format('MMDDYYYYTHHmmss')}`;
>   let path = '';
>   if (Platform.OS === 'android') {
>     // Use base64 - file does not work on Android
>     path = `data:text/csv;base64,${new Buffer(rows).toString("base64")}`;
>   } else {
>     // Write the file - base64 does not work on iOS
>     path = `${RNFS.TemporaryDirectoryPath}/${filename}.csv`;
>     await RNFS.writeFile(path, rows, 'utf8');
>   }
> 
>   // Temp fix for this issue 1405
>   Platform.OS === 'android' && setExporting(false);
> 
>   // Share file
>   await Share.open({
>     url: path,
>     failOnCancel: false,
>     subject: `MyApp - Export Data - ${filename}`,
>   });
> 
>   // Post share - never hit
> } catch (error) {
>   // Handle error - never hit
> }
> 
> setExporting(false);
> ```

This is exactly what is happening in my environment. I have not tested on iOS, but the promise is never getting resolved on android. My code is very similar to yours.

Running a Samsung Galaxy on Android 12.

Any advice or guidance would be appreciated!

**Comment by guistrutzki** [comment] 2023-07-21 19:10
I'm also having this issue. I have a loading layer controlled by a state, and I can't hide it, because any of try, catch or finally blocks aren't resolving the promise after executing Share.open(), so the app get stuck.

This only happens on Android, in iOS it works fine.
Using `react-native-share: 9.2.3`

**Comment by ncote3** [comment] 2023-07-27 15:53
Down grading to `react-native-share: 8.2.2` causes `Share.open()` to always throw regardless of success or rejection. While this at least resolves the promise, it unfortunately causes false error reporting.

**Comment by quoctruongkt** [comment] 2023-08-21 04:09
Have there been any solutions for this issue yet? I am using `react-native-share@9.2.3`

**Closed** 2023-08-28 19:16 UTC
Labels: bug
