### ISSUE TITLE
Is it possible to share not only image for Instagram?

### ISSUE THREAD

**Issue by sebazh** [react-native-share/react-native-share#1096] opened 2021-09-21 11:40 UTC
Hi guys, thank you for this awesome package.

We faced with a problem that we can share only image to Instagram, but we need to share text + image.
Tried Share.open and Share.openSingle. Caption is not populated with any of these params: title, message, subject etc.

Atm, sharing the following way:
```
const shareOptions = {
	url: 'data:image/png;base64,' + data,
	social: Share.Social.INSTAGRAM,
	forceDialog: true,
};
await Share.shareSingle(shareOptions);
```
and 
```
await Share.open({
	failOnCancel: false,
	message,
	subject,
	url: 'data:image/png;base64,' + data,
});
```

Could someone make a hint how to add some text or link to caption please? And is it doable at all? Thanks in advance

**Comment by karna419** [comment] 2021-10-10 06:34
Duplicate of #[https://github.com/react-native-share/react-native-share/issues/1108](URL)

**Closed** 2021-10-10 21:00 UTC
Labels: question
