### ISSUE TITLE
Android Share to Stories exception on Release

### ISSUE THREAD

**Issue by hongzhou85** [react-native-share/react-native-share#1101] opened 2021-09-27 01:24 UTC
Android share to story following the example:

`const shareOptions = {
                    title: 'Thank you',
                    url: uri,
                    backgroundImage: uri,
                    social: Share.Social.INSTAGRAM_STORIES,
                    failOnCancel: false,
                  }
`
`const ShareResponse = await Share.shareSingle(shareOptions)`
`setResult(JSON.stringify(ShareResponse, null, 2))`

Fatal Exception: com.facebook.react.uimanager.IllegalViewOperationException: Trying to resolve view with tag 31623 which doesn't exist
       at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveView(NativeViewHierarchyManager.java:100)
       at fr.greweb.reactnativeviewshot.ViewShot.execute(ViewShot.java:171)
       at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:571)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:917)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1028)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:48)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1088)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
       at android.view.Choreographer.doCallbacks(Choreographer.java:809)
       at android.view.Choreographer.doFrame(Choreographer.java:740)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8595)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by mikehardy** [comment] 2021-09-27 15:48
If the stack has a react-native-share object in there, it's a bug here, if not, it's not. This looks like maybe a react-native issue
Either way, even though I am sure this is frustrating, you have not included any information that could lead to a reproduction of this, and as such there's no action to take here, so I'm going to close it.

A high quality issue report would follow this as a general guide https://stackoverflow.com/help/minimal-reproducible-example

**Closed by mikehardy** 2021-09-27 15:48 UTC

**Comment by mikehardy** [comment] 2021-09-27 16:15
Still no example to reproduce it though, how can anyone help you? For all I know you are on react-native 0.59 and version 1 of this library, right? :shrug: 

Standard drill for release vs debug issues on android is to turn off minimize for release build (or enable it for debug) to see if it is the R8 shrinker removing something and you need to alter your proguard file. Second idea is to run it in Android Studio and catch it then inspect things.

But I don't reproduce the issue personally and don't have a reproduction so I have no further time for it, sorry
